# Generated by Django 4.0.5 on 2022-09-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_codregistro_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='codregistro',
        ),
    ]
