# Generated by Django 4.0.5 on 2022-08-31 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_project_is_active_remove_project_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'categotira',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
