# Generated by Django 4.0.5 on 2022-08-31 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_categoria', to='portfolio.category', verbose_name='categoria'),
            preserve_default=False,
        ),
    ]
