# Generated by Django 4.0.5 on 2022-08-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categoria',
        ),
        migrations.CreateModel(
            name='tipoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categoria', to='portfolio.category', verbose_name='categoria')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.ManyToManyField(to='portfolio.tipocategory'),
        ),
    ]
