# Generated by Django 4.0.5 on 2022-09-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_categoria_tipocategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='tipocategory',
            options={'verbose_name': 'Tipocategoria', 'verbose_name_plural': 'Tipocategorias'},
        ),
    ]
