# Generated by Django 4.0.5 on 2022-09-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_category_options_alter_tipocategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocategory',
            old_name='categoria',
            new_name='tipocategoria',
        ),
    ]
