# Generated by Django 4.0.5 on 2022-09-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_categoria_tipocategory_tipocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tipocategorias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categorias',
            field=models.CharField(choices=[('0', 'Dislexia'), ('1', 'Disortografía')], default='', max_length=1, verbose_name='categorias'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='categoria',
        ),
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_categoria', to='portfolio.category', verbose_name='categoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='tipoCategory',
        ),
    ]
