# Generated by Django 4.0.5 on 2022-09-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_categoria_project_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='subcategoria',
            field=models.ManyToManyField(to='portfolio.subcategory'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='categoria',
        ),
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='portfolio.category'),
        ),
    ]
