# Generated by Django 4.0.5 on 2022-09-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_subcategory_category_project_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
