# Generated by Django 4.0.5 on 2022-09-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_project_subcategoria_alter_project_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(choices=[('0', 'Dislexia'), ('1', 'Disortografía'), ('2', 'Digrafía'), ('3', 'Discalculia'), ('4', 'Superdotación'), ('5', 'Altas capacidades'), ('6', 'Talentos'), ('7', 'Trastorno por déficit de atención (TDA)'), ('8', 'TDA con hiperactividad (TDA-H)'), ('9', 'Ceguera total'), ('10', 'Baja Visión'), ('12', 'Sordera'), ('13', 'Hipoacusia'), ('14', 'Musculo esquelético'), ('15', 'Trastorno autista'), ('16', 'Trastorno de Asperger'), ('17', 'Trastorno de Rett'), ('18', 'Trastorno de desintegración infantil')], max_length=2, verbose_name='categorias')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='subcategoria',
            field=models.ManyToManyField(to='portfolio.subcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
