# Generated by Django 4.0.5 on 2022-09-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_subcategory_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'subcategoria', 'verbose_name_plural': 'subcategorias'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='categoria',
        ),
    ]
