# Generated by Django 4.0.5 on 2022-09-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategoria',
            field=models.CharField(max_length=200, verbose_name='SubCategoria'),
        ),
    ]
