# Generated by Django 4.0.5 on 2022-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_remove_project_likes_project_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.BooleanField(null=True),
        ),
    ]
