# Generated by Django 4.0.5 on 2022-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_remove_project_likes_project_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default='', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
